import type { Metadata } from "next";
import "./globals.css";
import { poppinsFont, wixMadeforDisplayFont } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${wixMadeforDisplayFont.variable} ${poppinsFont.variable} antialiased  font-secondary`}
      >
        {children}
      </body>
    </html>
  );
}
